### ISSUE TITLE
encontros sorocabajs @braziljs newsletter

### ISSUE THREAD

**Issue by felipebernardes** [sorocabajs/meta#2]
fala galera! beleza?

estava lendo a weekly da braziljs e lembrei do sjs ao ler a parte de eventos. acho que a gente deveria divulgar os próximos encontros lá, que tal? :smile:

**Comment by brenolf** [comment]
Ia ser legal mesmo, a gente já estava listado no [BrazilJS.org](http://braziljs.org/eventos/). Quando a gente souber mais ou menos a data da próxima a gente manda lá também :smiley:

**Comment by felipebernardes** [comment]
show! valeu, @brenolf
